In [ ]:
import numpy as np

data = np.load('/Volumes/sgrolab/jennifer/cryolite/cryolite_mixin_test53_2025-02-22/old_optical_flow_3Dresults/optical_flow_confidence_20250707_150609.npy')

In [3]:
data.shape

(217, 1906, 1440)

In [4]:
data = np.load('/Volumes/sgrolab/jennifer/cryolite/cryolite_mixin_test53_2025-02-22/optical_flow_results/optical_flow_vx_20250707_150609.npy')

In [5]:
data[0]

array([[-0.05049644, -0.04960804, -0.04769761, ...,  0.04632924,
         0.03838224,  0.03170176],
       [-0.04167922, -0.04214462, -0.04155021, ...,  0.0325715 ,
         0.02646702,  0.02147583],
       [-0.03480755, -0.03608761, -0.03625581, ...,  0.02189842,
         0.01707493,  0.0134702 ],
       ...,
       [-0.52125305, -0.4842498 , -0.41405213, ...,  0.16410527,
         0.12977123,  0.09837314],
       [-0.5614946 , -0.507297  , -0.41469464, ...,  0.1678442 ,
         0.1315793 ,  0.09874211],
       [-0.6092462 , -0.52717185, -0.39633206, ...,  0.16688511,
         0.12998599,  0.09693472]], dtype=float32)

In [4]:
data = np.load('/Volumes/sgrolab/jennifer/cryolite/cryolite_mixin_test53_2025-02-22/optical_flow_3Dresults/20/optical_flow_vy.npy')

In [5]:
data[0]

array([[-0.2562967 , -0.20238017, -0.13349214, ...,  0.52922887,
         0.3299401 ,  0.12061074],
       [-0.14537722, -0.09499575, -0.02614147, ...,  0.6357464 ,
         0.43252042,  0.21901941],
       [-0.05884673, -0.01309123,  0.05604485, ...,  0.75272363,
         0.5560197 ,  0.34169152],
       ...,
       [-0.01936094, -0.01939694, -0.01914372, ..., -0.23761266,
        -0.26240808, -0.2888977 ],
       [-0.02047568, -0.02055337, -0.02036832, ..., -0.2454604 ,
        -0.26714364, -0.28965384],
       [-0.02148445, -0.02139955, -0.02110635, ..., -0.2337143 ,
        -0.25130144, -0.26895276]], dtype=float32)

In [1]:
import numpy as np 

data = np.load('/Volumes/sgrolab/jennifer/cryolite/cryolite_mixin_test53_2025-02-22/optical_flow_3Dresults/140/optical_flow_confidence.npy')


In [3]:
data.shape

(217, 1906, 1440)

In [4]:
data[200]

array([[ 0.0000000e+00,  0.0000000e+00,  7.2759576e-12, ...,
         2.9103830e-11, -2.9103830e-11,  0.0000000e+00],
       [ 0.0000000e+00,  2.9103830e-11,  0.0000000e+00, ...,
         1.1641532e-10, -2.9103830e-11,  5.8207661e-11],
       [ 2.9103830e-11,  0.0000000e+00,  2.9103830e-11, ...,
        -2.9103830e-11, -2.9103830e-11,  1.4551915e-11],
       ...,
       [ 5.8207661e-11, -5.8207661e-11,  0.0000000e+00, ...,
         1.4551915e-11, -2.9103830e-11, -2.9103830e-11],
       [ 1.1641532e-10, -5.8207661e-11, -2.9103830e-11, ...,
         0.0000000e+00, -2.9103830e-11,  0.0000000e+00],
       [-5.8207661e-11, -5.8207661e-11,  0.0000000e+00, ...,
         2.9103830e-11,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [3]:
import numpy as np

data = np.load('/Volumes/sgrolab/jennifer/cryolite/cryolite_mixin_test53_2025-02-22/optical_flow_3Dresults/134/magnitude_map.npy')

In [2]:
np.shape

<function shape at 0x1063c6cf0>

In [4]:
data[0]

array([0.98041642, 0.974159  , 0.96542704, ..., 0.28600013, 0.28542572,
       0.28492218])

In [5]:
data[1]

array([0.96050215, 0.95376223, 0.94460273, ..., 0.28682241, 0.28626153,
       0.28578216])

In [6]:
data[10]

array([0.75844276, 0.75060433, 0.74080652, ..., 0.29463115, 0.29293731,
       0.29152226])

In [7]:
data[5]

array([0.87454081, 0.86680412, 0.85690558, ..., 0.28556454, 0.28496906,
       0.28453428])